#!/bin/sh
#
# cherryd for FreeBSD 7.0 rc.d usage, by Michiel Overtoom, motoom@xs4all.nl
# based on http://www.djangosnippets.org/snippets/1050/ by David Blewett
#

# PROVIDE: cherryd
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add these lines to /etc/rc.conf:
#
#  cherryd_enable="YES"
#  cherryd_wwwdir="/www" # where the site .py and .conf files are
#  cherryd_flags="-c CONFIG -i IMPORTS"  # specify config file(s) and imports to use
#
# Make sure the cherryd script is chmodded as executable.
#
# Before playing interactively with this script and not having added the
# config lines to rc.conf yet, you might want to do: setenv cherryd_enable YES

. /etc/rc.subr

# On FreeBSD 7, the default location for python is /usr/local/bin,
# but during boot /usr/local/bin isn't in the PATH yet.
# The cherryd script uses the following shebang line: #!/usr/bin/env python
# to make that shebang work, we have to add /usr/local/bin to the PATH.
PATH="$PATH:/usr/local/bin"

name="cherryd"
rcvar=`set_rcvar`
pidfile="/var/run/${name}.pid"

command_interpreter="python"
command="/usr/local/lib/python2.5/site-packages/cherrypy/${name}"
command_args="-d -p $pidfile ${cherryd_flags}"

start_cmd="echo \"Starting ${name}.\"; cd ${cherryd_wwwdir}; ${command} ${command_args}"

load_rc_config $name
run_rc_command "$1"
